[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["--cov=gnn_tracking_hpo", "-ra", "--showlocals", "--strict-markers", "--strict-config", "--cov-branch"]
xfail_strict = true

[tool.pycln]
all = true
